Repository TacticalBaconDevs/TBMod, pull requests merged in 2018-11, with the labels that each got.

#75 Animation ai
  addons/TBMod_arsenal/arsenal/fn_arsenalUSAVietnam.sqf
  addons/TBMod_building/functions/fn_buildingPersistence.sqf
  addons/TBMod_main/functions/fn_animationAI.sqf
  addons/TBMod_main/functions/fn_clearCache.sqf
  addons/TBMod_main/functions/fn_persistence.sqf
  addons/TBMod_rhs/CfgVehicles.hpp
  addons/TBMod_unsung/CfgVehicles.hpp
  addons/TBMod_unsung/config.cpp
Labels: need review

#81 BW Werferkiste
  addons/TBMod_nachschub/configs/CfgVehicles_BW.hpp
Labels: need review

#68 Arsenal Russen
  addons/TBMod_arsenal/arsenal/fn_arsenalRUSS.sqf
  addons/TBMod_arsenal/functions/fn_loadDefault.sqf
Labels: need review

#67 Problem mit Eric slingload
  addons/TBMod_ADVSlingload/XEH_postClientInit.sqf
  addons/TBMod_ADVSlingload/functions/fn_addAttachAction.sqf
  addons/TBMod_ADVSlingload/functions/fn_dropRope.sqf
  addons/TBMod_ADVSlingload/functions/fn_dropRopefromChopper.sqf
  addons/TBMod_ADVSlingload/functions/fn_putBackRope.sqf
  addons/TBMod_ADVSlingload/functions/fn_startRopeinHandsPFH.sqf
Labels: bug, need review, needs testing

#83 Misc stuff
  addons/#TBMod_unsung/$PBOPREFIX$
  addons/#TBMod_unsung/CfgEditorSubcategories.hpp
  addons/#TBMod_unsung/CfgVehicles.hpp
  addons/#TBMod_unsung/config.cpp
  addons/TBModExt_monitoring/$PBOPREFIX$
  addons/TBModExt_monitoring/CfgFunctions.hpp
  addons/TBModExt_monitoring/ExtendedEventHandlers.hpp
  addons/TBModExt_monitoring/ReadMe.md
  addons/TBModExt_monitoring/XEH_preServerInit.sqf
  addons/TBModExt_monitoring/config.cpp
  addons/TBModExt_monitoring/monitor.fsm
  addons/TBMod_arsenal/functions/fn_whitelist.sqf
  addons/TBMod_main/XEH_preInit.sqf
  addons/TBMod_main/configs/Cfg3DEN.hpp
  addons/TBMod_main/configs/ExtendedEventHandlers.hpp
  addons/TBMod_main/functions/fn_chatCommands.sqf
  addons/TBMod_main/functions/fn_miscStuff.sqf
  addons/TBMod_main/functions/fn_recoilSystem.sqf
  addons/TBMod_zusatzStuff/eos/CfgVehicles.hpp
  addons/TBMod_zusatzStuff/eos/core/fn_bastionCore.sqf
  infos/debugCode.sqf
Labels: WIP, enhancement
