Repository TacticalBaconDevs/TBMod, pull requests merged in 2018-10, with the labels that each got.

#55 Umbennenung von items to liveMonitor
  addons/TBMod_items/$PBOPREFIX$
  addons/TBMod_items/XEH_postInit.sqf
  addons/TBMod_items/config.cpp
  addons/TBMod_items/functions/liveMonitor/fn_lm_canShow.sqf
  addons/TBMod_items/functions/liveMonitor/fn_lm_initialize.sqf
  addons/TBMod_items/functions/liveMonitor/fn_lm_loop.sqf
  addons/TBMod_items/functions/liveMonitor/fn_lm_remove.sqf
  addons/TBMod_liveMonitor/$PBOPREFIX$
  addons/TBMod_liveMonitor/ReadMe.md
  addons/TBMod_liveMonitor/UI/common.hpp
  addons/TBMod_liveMonitor/UI/common_EditorWrapper.hpp
  addons/TBMod_liveMonitor/UI/liveMonitor.hpp
  addons/TBMod_liveMonitor/XEH_postInit.sqf
  addons/TBMod_liveMonitor/config.cpp
  addons/TBMod_liveMonitor/configs/CfgFunctions.hpp
  addons/TBMod_liveMonitor/configs/CfgVehicles.hpp
  addons/TBMod_liveMonitor/configs/CfgWeapons.hpp
  addons/TBMod_liveMonitor/configs/ExtendedEventHandlers.hpp
  addons/TBMod_liveMonitor/configs/RscTitles.hpp
  addons/TBMod_liveMonitor/functions/fn_animated.sqf
  addons/TBMod_liveMonitor/functions/fn_canShow.sqf
  addons/TBMod_liveMonitor/functions/fn_initialize.sqf
  addons/TBMod_liveMonitor/functions/fn_loop.sqf
  addons/TBMod_liveMonitor/functions/fn_remove.sqf
  addons/TBMod_liveMonitor/models/liveMonitor.p3d
  addons/TBMod_liveMonitor/pictures/Arrow_Down.paa
  addons/TBMod_liveMonitor/pictures/Arrow_Up.paa
  addons/TBMod_liveMonitor/pictures/heartbeat.paa
  addons/TBMod_liveMonitor/pictures/heartline.paa
  addons/TBMod_liveMonitor/pictures/liveMonitor.paa
  addons/TBMod_liveMonitor/pictures/liveMonitorBackground.paa
  addons/TBMod_liveMonitor/pictures/medical_cross_lm.paa
Labels: needs testing

#54 Vietnam-USA ThemenArsenal
  TB_MAINCORE.VR/init.sqf
  addons/TBMod_arsenal/XEH_postClientInit.sqf
  addons/TBMod_arsenal/arsenal/fn_arsenalThemen.sqf
  addons/TBMod_arsenal/arsenal/fn_arsenalUSAVietnam.sqf
  addons/TBMod_arsenal/config.cpp
  addons/TBMod_arsenal/configs/CfgEditorSubcategories.hpp
  addons/TBMod_arsenal/configs/CfgFunctions.hpp
  addons/TBMod_arsenal/configs/CfgVehicles.hpp
  addons/TBMod_arsenal/functions/fn_actionMain.sqf
  addons/TBMod_arsenal/functions/fn_loadDefault.sqf
  addons/TBMod_arsenal/functions/fn_modifierMainAction.sqf
  addons/TBMod_arsenal/functions/fn_setArsenal.sqf
  addons/TBMod_liveMonitor/UI/liveMonitor.hpp
  addons/TBMod_main/configs/CfgEditorCategories.hpp
  addons/TBMod_main/configs/CfgEditorSubcategories.hpp
  addons/TBMod_nachschub/config.cpp
  addons/TBMod_nachschub/configs/CfgEditorCategories.hpp
  addons/TBMod_nachschub/configs/CfgEditorSubcategories.hpp
  addons/TBMod_nachschub/configs/CfgVehicles.hpp
  addons/TBMod_unsung/$PBOPREFIX$
  addons/TBMod_unsung/CfgEditorSubcategories.hpp
  addons/TBMod_unsung/CfgVehicles.hpp
  addons/TBMod_unsung/config.cpp
Labels: need review

#58 Darky vietnam arsenal Anpassungen
  addons/TBMod_arsenal/arsenal/fn_arsenalUSAVietnam.sqf
Labels: dependency
