Repository TacticalBaconDevs/TBMod, pull requests merged in 2019-04, with the labels that each got.

#178 Neues Sanisystem
  addons/TBMod_arsenal/arsenal/fn_arsenalBW.sqf
  addons/TBMod_arsenal/arsenal/fn_arsenalUSA.sqf
  addons/TBMod_arsenal/functions/fn_loadDefault.sqf
  addons/TBMod_arsenal/functions/fn_setArsenal.sqf
  addons/TBMod_main/configs/ACE_Medical_Treatments.hpp
  addons/TBMod_main/functions/fn_doorBreach.sqf
  addons/TBMod_nachschub/configs/CfgVehicles.hpp
Labels: need review

#181 Arsenal/inventar
  addons/TBMod_arsenal/arsenal/fn_arsenalBW.sqf
  addons/TBMod_arsenal/arsenal/fn_arsenalUSA.sqf
  addons/TBMod_arsenal/functions/fn_setArsenal.sqf
Labels: WIP

#187 TFAR Timeout
  addons/TBMod_main/functions/fn_miscStuff.sqf
Labels: need review

#189 Eric eron ace medical tool tips
  addons/TBMod_arsenal/functions/fn_setArsenal.sqf
  addons/TBMod_main/configs/ACE_Medical_Treatments.hpp
  addons/TBMod_main/configs/CfgVehicles.hpp
  addons/TBMod_main/configs/CfgWeapons.hpp
  addons/TBMod_main/functions/fn_UpDown.sqf
  addons/TBMod_main/functions/fn_upDown.sqf
  addons/disabled/TBMod_liveMonitor/$PBOPREFIX$
  addons/disabled/TBMod_liveMonitor/ReadMe.md
  addons/disabled/TBMod_liveMonitor/UI/common.hpp
  addons/disabled/TBMod_liveMonitor/UI/common_EditorWrapper.hpp
  addons/disabled/TBMod_liveMonitor/UI/liveMonitor.hpp
  addons/disabled/TBMod_liveMonitor/XEH_postInit.sqf
  addons/disabled/TBMod_liveMonitor/config.cpp
  addons/disabled/TBMod_liveMonitor/configs/CfgFunctions.hpp
  addons/disabled/TBMod_liveMonitor/configs/CfgVehicles.hpp
  addons/disabled/TBMod_liveMonitor/configs/CfgWeapons.hpp
  addons/disabled/TBMod_liveMonitor/configs/ExtendedEventHandlers.hpp
  addons/disabled/TBMod_liveMonitor/configs/RscTitles.hpp
  addons/disabled/TBMod_liveMonitor/functions/fn_animated.sqf
  addons/disabled/TBMod_liveMonitor/functions/fn_canShow.sqf
  addons/disabled/TBMod_liveMonitor/functions/fn_initialize.sqf
  addons/disabled/TBMod_liveMonitor/functions/fn_loop.sqf
  addons/disabled/TBMod_liveMonitor/functions/fn_remove.sqf
  addons/disabled/TBMod_liveMonitor/models/liveMonitor.p3d
  addons/disabled/TBMod_liveMonitor/pictures/Arrow_Down.paa
  addons/disabled/TBMod_liveMonitor/pictures/Arrow_Up.paa
  addons/disabled/TBMod_liveMonitor/pictures/heartbeat.paa
  addons/disabled/TBMod_liveMonitor/pictures/heartline.paa
  addons/disabled/TBMod_liveMonitor/pictures/liveMonitor.paa
  addons/disabled/TBMod_liveMonitor/pictures/liveMonitorBackground.paa
  addons/disabled/TBMod_liveMonitor/pictures/medical_cross_lm.paa
Labels: need review

#193 Anpassungen misc
  addons/TBMod_main/XEH_preInit.sqf
  addons/TBMod_main/functions/fn_chatCommands.sqf
  addons/TBMod_main/functions/fn_doorBreach.sqf
  addons/TBMod_main/functions/fn_shortcuts.sqf
Labels: need review

#192 TBMod Builder
  #buildingTools/README.txt
  #buildingTools/pbo_alle.bat
  #buildingTools/pbo_einzeln.bat
  .gitignore
  TBMod_Builder.jar
  monitoring/SQLite.Interop.dll
  monitoring/System.Data.SQLite.dll
  monitoring/TBModExt_Monitoring_x64.dll
  monitoring/TBMod_Monitor.exe
  monitoring/database.sqlite
Labels: need review, needs testing

#199 Eron Sani-Änderungen 13.04
  addons/TBMod_arsenal/functions/fn_setAttributes.sqf
  addons/TBMod_main/configs/ACE_Medical_Treatments.hpp
  addons/TBMod_main/functions/fn_calcTreatmentTime.sqf
Labels: need review

#198 Builder 1.0.1
  TBMod_Builder.jar
Labels: need review

#200 IV Transfer abhängig von Location; MiscStuff
  addons/TBMod_main/XEH_preInit.sqf
  addons/TBMod_main/configs/CfgFunctions.hpp
  addons/TBMod_main/functions/fn_calcTreatmentTime.sqf
  addons/TBMod_main/functions/fn_shortcuts.sqf
  addons/TBMod_main/replacement/fn_getBloodVolumeChange.sqf
  circle.yml
Labels: need review

#203 Stuff
  TBMod_Builder.jar
  addons/TBMod_advSlingload/functions/fn_addAttachAction.sqf
  addons/TBMod_building/XEH_preInit.sqf
  addons/TBMod_building/config.cpp
  addons/TBMod_building/configs/CfgVehicles.hpp
  addons/TBMod_building/configs/ExtendedEventHandlers.hpp
  addons/TBMod_building/functions/fn_initItem.sqf
  addons/TBMod_building/functions/fn_placePlaceables.sqf
  addons/TBMod_main/XEH_preInit.sqf
  addons/TBMod_main/functions/fn_recoilSystem.sqf
  addons/TBMod_main/replacement/fn_getBloodVolumeChange.sqf
  addons/TBMod_nachschub/functions/fn_createSupply.sqf
  addons/TBMod_zeus/config.cpp
  addons/TBMod_zeus/configs/CfgFunctions.hpp
  addons/TBMod_zeus/configs/CfgVehicles.hpp
  addons/TBMod_zeus/functions/fn_moduleUnflipVehicle.sqf
  addons/TBMod_zeus/functions/fn_unflipVehicle.sqf
  addons/TBMod_zusatzStuff/eos/functions/fn_transportUnload.sqf
Labels: need review

#204 Den KommandoMörser Spitzname "shukarisMörser" integriert
  TBMod_Builder.jar
  addons/TBMod_arsenal/arsenal/fn_arsenalUSA.sqf
  addons/TBMod_main/functions/fn_displayName.sqf
  addons/TBMod_nachschub/configs/CfgVehicles.hpp
  addons/TBMod_nachschub/configs/CfgVehicles_USA.hpp
  addons/TBMod_vz99/$PBOPREFIX$
  addons/TBMod_vz99/ReadMe.md
  addons/TBMod_vz99/XEH_postInit.sqf
  addons/TBMod_vz99/config.cpp
  addons/TBMod_vz99/configs/CfgAmmo.hpp
  addons/TBMod_vz99/configs/CfgFunctions.hpp
  addons/TBMod_vz99/configs/CfgMagazines.hpp
  addons/TBMod_vz99/configs/CfgVehicles.hpp
  addons/TBMod_vz99/configs/CfgWeapons.hpp
  addons/TBMod_vz99/configs/ExtendedEventHandlers.hpp
  addons/TBMod_vz99/data/front2_ca.paa
  addons/TBMod_vz99/data/glass.rvmat
  addons/TBMod_vz99/data/model.cfg
  addons/TBMod_vz99/data/plastic.rvmat
  addons/TBMod_vz99/data/vz99_carry.p3d
  addons/TBMod_vz99/data/vz99_vehicle.p3d
  addons/TBMod_vz99/data/water.rvmat
  addons/TBMod_vz99/functions/fn_canDeployWeapon.sqf
  addons/TBMod_vz99/functions/fn_canPickupWeapon.sqf
  addons/TBMod_vz99/functions/fn_canSelectNextMagazine.sqf
  addons/TBMod_vz99/functions/fn_doDeployWeapon.sqf
  addons/TBMod_vz99/functions/fn_doPickupWeapon.sqf
  addons/TBMod_vz99/functions/fn_doReload.sqf
  addons/TBMod_vz99/functions/fn_doSelectNextMagazine.sqf
  addons/TBMod_vz99/functions/fn_handleFired.sqf
  addons/TBMod_vz99/functions/fn_handlePlayerVehicleChanged.sqf
  addons/TBMod_vz99/functions/fn_levelToGround.sqf
  addons/TBMod_vz99/ui/action_mortar_ca.paa
  addons/TBMod_vz99/ui/action_shell_ca.paa
  addons/TBMod_vz99/ui/shell_ca.paa
  addons/TBMod_vz99/ui/weaponSide_ca.paa
Labels: need review

#205 Atmosphären Modul 'Verstärkung' hinzugefügt
  addons/TBMod_arsenal/functions/fn_whitelist.sqf
  addons/TBMod_eden/config.cpp
  addons/TBMod_eden/configs/CfgFunctions.hpp
  addons/TBMod_eden/configs/CfgVehicles.hpp
  addons/TBMod_eden/functions/fn_atmoCoreAction.sqf
  addons/TBMod_eden/functions/fn_moduleAtmoCore.sqf
  addons/TBMod_main/XEH_preInit.sqf
  addons/TBMod_main/configs/CfgFunctions.hpp
  addons/TBMod_main/functions/fn_crashHelferClient.sqf
  addons/TBMod_main/functions/fn_debug.sqf
  addons/TBMod_main/functions/fn_deleteIfNotSeen.sqf
  addons/TBMod_rhs/CfgMagazines.hpp
  addons/TBMod_vz99/configs/CfgAmmo.hpp
  addons/TBMod_vz99/configs/CfgMagazines.hpp
  addons/TBMod_vz99/configs/CfgWeapons.hpp
Labels: need review

#206 WIP: Default layouts
  addons/TBMod_arsenal/arsenal/fn_arsenalBW.sqf
  addons/TBMod_arsenal/arsenal/fn_arsenalUSA.sqf
  addons/TBMod_arsenal/arsenal/fn_arsenalVANILLA.sqf
  addons/TBMod_arsenal/functions/fn_loadDefault.sqf
  addons/TBMod_main/configs/CfgVehicles.hpp
Labels: need review
