Repository TacticalBaconDevs/TBMod, pull requests merged in 2019-07, with the labels that each got.

#261 Animations abbrechbar && safe überarbeitet
  addons/TBMod_eden/configs/Cfg3DEN.hpp
  addons/TBMod_eden/functions/fn_animationAI.sqf
  addons/TBMod_main/functions/fn_safe.sqf
Labels: need review

#268 ivChanges
  .gitignore
  addons/TBMod_main/functions/fn_miscStuff.sqf
  addons/TBMod_main/replacement/fn_getBloodVolumeChange.sqf
Labels: enhancement, need review

#264 Rufnamen
  .gitignore
  addons/TBMod_main/configs/CfgFunctions.hpp
  addons/TBMod_main/configs/CfgVehicles.hpp
  addons/TBMod_main/functions/fn_insertChildrenRufname.sqf
Labels: need review

#270 Skins/Bomben etc
  addons/TBMod_nachschub/configs/CfgVehicles.hpp
  addons/TBMod_rhs/CfgMagazines.hpp
  addons/TBMod_rhs/CfgVehicles.hpp
  addons/TBMod_rhs/CfgWeapons.hpp
  addons/TBMod_skins/configs/CfgEditorSubcategories.hpp
  addons/TBMod_skins/configs/CfgVehicles.hpp
  addons/TBMod_skins/pictures/vehicles/TB_Vehicles_BW_Strider_0.paa
  addons/TBMod_skins/pictures/vehicles/TB_Vehicles_L-159_1.paa
  addons/TBMod_skins/pictures/vehicles/TB_Vehicles_L-159_2.paa
  addons/TBMod_skins/pictures/vehicles/TB_Vehicles_Patria_AMW_1.paa
  addons/TBMod_skins/pictures/vehicles/TB_Vehicles_Patria_AMW_2.paa
  addons/TBMod_skins/pictures/vehicles/TB_Vehicles_Patria_AMW_3.paa
  addons/TBMod_skins/pictures/vehicles/TB_Vehicles_Strider_0.paa
  addons/TBMod_skins/pictures/vehicles/TB_Vehicles_Strider_1.paa
Labels: need review

#271 IV erhöht
  addons/TBMod_arsenal/functions/fn_setArsenal.sqf
  addons/TBMod_main/functions/fn_chatCommands.sqf
  addons/TBMod_medical/configs/ACE_Medical_Treatments.hpp
  addons/TBMod_medical/configs/CfgVehicles.hpp
  addons/TBMod_medical/configs/CfgWeapons.hpp
Labels: need review

#278 Fix Crashhelper
  addons/TBMod_main/functions/fn_crashHelferServer.sqf
Labels: needs testing

#280 Adds Chatcommand for Snipers
  addons/TBMod_main/functions/fn_chatCommands.sqf
Labels: needs testing

#274 .paa Dateien für Flaggen
  addons/TBMod_building/configs/CfgVehicles.hpp
  addons/TBMod_main/configs/CfgFunctions.hpp
  addons/TBMod_main/functions/fn_insertChildrenFlaggen.sqf
  addons/TBMod_skins/pictures/flags/Flagge_1.paa
  addons/TBMod_skins/pictures/flags/Flagge_2.paa
  addons/TBMod_skins/pictures/flags/Flagge_3.paa
  addons/TBMod_skins/pictures/flags/Flagge_4.paa
  addons/TBMod_skins/pictures/flags/Flagge_5.paa
  addons/TBMod_skins/pictures/flags/Flagge_6.paa
  addons/TBMod_skins/pictures/flags/Flagge_7.paa
  addons/TBMod_skins/pictures/flags/Flagge_8.paa
  addons/TBMod_skins/pictures/flags/Flagge_9.paa
  addons/TBMod_skins/pictures/flags/Flagge_Boko_Haram.paa
  addons/TBMod_skins/pictures/flags/Flagge_IS.paa
  addons/TBMod_skins/pictures/flags/Flagge_Taliban.paa
  addons/TBMod_skins/pictures/flags/Flagge_al-Shabaab.paa
Labels: help wanted, need review

#289 Anzahl von Adenosin auf 3 reduziert/teilweise Bandagen erweitert
  addons/TBMod_arsenal/functions/fn_loadDefault.sqf
Labels: need review
