Repository TacticalBaconDevs/TBMod, pull requests merged in 2020-05, with the labels that each got.

#475 RHS AGM-114K/M/N/L Raketen entfernt
  addons/rhs/CfgMagazines.hpp
Labels: need review

#481 SpEcTrUmDeViCe
  addons/spectrum/ReadMe.md
  addons/spectrum/XEH_PREP.hpp
  addons/spectrum/XEH_postClientInit.sqf
  addons/spectrum/XEH_preInit.sqf
  addons/spectrum/XEH_preStart.sqf
  addons/spectrum/config.cpp
  addons/spectrum/configs/ExtendedEventHandlers.hpp
  addons/spectrum/functions/fnc_calcSignal.sqf
  addons/spectrum/functions/fnc_findTransmitter.sqf
  addons/spectrum/script_component.hpp
Labels: EricReview&Merge

#487 Poppy Face
  addons/poppy/configs/CfgLoadouts.hpp
  addons/poppy/functions/fnc_setEquipment.sqf
  addons/poppy/script_component.hpp
Labels: kind/enhancement, need review

#489 Für das Mk17 angemessene Visiere
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
Labels: need review

#491 Tasks
  addons/persistence/functions/fnc_persistenceTasks.sqf
  addons/tasks/XEH_PREP.hpp
  addons/tasks/XEH_postServerInit.sqf
  addons/tasks/functions/fnc_execute.sqf
  addons/tasks/functions/fnc_loadTask.sqf
  addons/tasks/functions/fnc_loop.sqf
  addons/tasks/script_component.hpp
Labels: need review

#472 neuer Konzepttest
  addons/arsenal/XEH_PREP.hpp
  addons/arsenal/tests/fnc_baseWeaponTest.sqf
  addons/arsenal/tests/fnc_checkItems.sqf
  addons/arsenal/tests/fnc_test.sqf
  addons/main/XEH_PREP.hpp
  addons/main/tests/fnc_test.sqf
  addons/nachschub/tests/fnc_kistenCheckTest.sqf
Labels: EricReview&Merge

#492 Tasks - Reworked
  addons/persistence/functions/fnc_persistenceTasks.sqf
  addons/tasks/XEH_PREP.hpp
  addons/tasks/XEH_postServerInit.sqf
  addons/tasks/functions/fnc_execute.sqf
  addons/tasks/functions/fnc_loadTask.sqf
  addons/tasks/functions/fnc_loop.sqf
  addons/tasks/script_component.hpp
Labels: EricReview&Merge, kind/enhancement

#494 Fix ShowMedicalType in VehicleInfo
  addons/building/functions/fnc_modifierShowVehicleType.sqf
Labels: kind/bug, need review

#480 BW/UK/LDF Arsenale optimized
  addons/arsenal/arsenale/fnc_arsenalBW.sqf
  addons/arsenal/arsenale/fnc_arsenalUK.sqf
  addons/arsenal/arsenale/themen/fnc_arsenalLDF.sqf
  addons/arsenal/functions/fnc_whitelist.sqf
Labels: need review, needs testing

#497 Poppy Items +1 Fix
  addons/poppy/functions/fnc_addItems.sqf
Labels: kind/bug, need review

#493 spawns/waitUntils/sleeps raus -> unscheduled
  TBModExtension_Logging.dll
  TBModExtension_Persistence.dll
  TBModExtension_x64.dll
  addons/arsenal/XEH_postClientInit.sqf
  addons/arsenal/functions/fnc_waitUntilLoaded.sqf
  addons/arsenal/tests/fnc_test.sqf
  addons/building/configs/CfgVehicles.hpp
  addons/building/functions/fnc_initItem.sqf
  addons/building/functions/fnc_moduleRessourcenFahrzeug.sqf
  addons/building/functions/fnc_placePlaceablesBig.sqf
  addons/config/configs/CfgMagazines.hpp
  addons/eden/configs/Cfg3DEN.hpp
  addons/eden/functions/fnc_animationAI.sqf
  addons/eden/functions/fnc_atmoCoreAction.sqf
  addons/eden/functions/fnc_inkognitoSystem.sqf
  addons/eden/functions/fnc_keysForAI.sqf
  addons/eden/functions/fnc_moduleAtmoCore.sqf
  addons/eden/functions/fnc_moduleAtmoFireSuppression.sqf
  addons/eden/functions/fnc_moduleAtmoShootingRange.sqf
  addons/eden/functions/fnc_moduleInjured.sqf
  addons/eden/functions/fnc_sitAI.sqf
  addons/eos/configs/ExtendedEventHandlers.hpp
  addons/main/XEH_postClientInit.sqf
  addons/main/XEH_postInit.sqf
  addons/main/XEH_postServerInit.sqf
  addons/main/configs/CfgVehicles.hpp
  addons/main/functions/fnc_actionTeleportKamerad.sqf
  addons/main/functions/fnc_chatCommands.sqf
  addons/main/functions/fnc_crashHelferClient.sqf
  addons/main/functions/fnc_deleteIfNotSeen.sqf
  addons/main/functions/fnc_firstJoin.sqf
  addons/main/functions/fnc_forceRagdoll.sqf
  addons/main/functions/fnc_insertChildrenFOB.sqf
  addons/main/functions/fnc_insertChildrenGruppen.sqf
  addons/main/functions/fnc_insertChildrenKameraden.sqf
  addons/main/functions/fnc_isTBMission.sqf
  addons/main/functions/fnc_miscStuff.sqf
  addons/main/functions/fnc_safe.sqf
  addons/main/functions/fnc_teleport.sqf
  addons/main/functions/tb_RscDisplayGarage.sqf
  addons/main/tests/fnc_test.sqf
  addons/menubutton/config.cpp
  addons/menubutton/joinServer.sqf
  addons/nachschub/configs/CfgVehicles.hpp
  addons/nachschub/functions/fnc_createSupply.sqf
  addons/nachschub/tests/fnc_test.sqf
  addons/persistence/functions/fnc_modulepersistenceEDEN.sqf
  addons/persistence/functions/fnc_persistenceEDEN.sqf
  addons/persistence/functions/fnc_ping.sqf
  addons/rhs/CfgWeapons.hpp
  addons/spectrum/XEH_postClientInit.sqf
  addons/spectrum/XEH_postServerInit.sqf
  addons/spectrum/functions/fnc_initUavs.sqf
  addons/spectrum/functions/fnc_spectrumActions.sqf
  addons/warlords/XEH_preServerInit.sqf
  infos/inheritance/#README.txt
  infos/inheritance/inheritance_Vanilla+CBA+BWA-2.2.data
  infos/inheritance/inheritance_Vanilla+RHS-0.5.2.data
  infos/inheritance/inheritance_Vanilla.data
Labels: EricReview&Merge, kind/enhancement
