Repository TacticalBaconDevs/TBMod, pull requests merged in 2020-04, with the labels that each got.

#458 Bloodpressure Action Fix
  addons/medical/configs/ACE_Medical_Treatments.hpp
Labels: kind/bug, need review

#457 Recoilsystem fix
  addons/main/functions/fnc_recoilSystem.sqf
Labels: kind/bug, need review

#448 Addon-Tests
  addons/arsenal/XEH_PREP.hpp
  addons/arsenal/arsenale/fnc_arsenalBW.sqf
  addons/arsenal/arsenale/fnc_arsenalRUSS.sqf
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
  addons/arsenal/arsenale/fnc_arsenalVANILLA.sqf
  addons/arsenal/configs/CfgVehicles.hpp
  addons/arsenal/functions/fnc_loadDefault.sqf
  addons/arsenal/tests/fnc_checkArsenalsTest.sqf
  addons/arsenal/tests/fnc_checkItems.sqf
  addons/arsenal/tests/fnc_defaultLoadoutTest.sqf
  addons/arsenal/tests/fnc_test.sqf
  addons/main/XEH_PREP.hpp
  addons/main/functions/fnc_chatCommands.sqf
  addons/main/functions/fnc_uniqueArray.sqf
  addons/nachschub/XEH_PREP.hpp
  addons/nachschub/tests/fnc_kistenCheckTest.sqf
  addons/nachschub/tests/fnc_test.sqf
  addons/zeus/configs/ACE_ZeusActions.hpp
Labels: kind/bug, need review

#450 Gunship+Supply Korrektur
  addons/nachschub/configs/CfgVehicles.hpp
  addons/rhs/CfgVehicles.hpp
Labels: WIP, help wanted

#462 calcTreatment Einstellungen & healthRegen
  addons/main/config.cpp
  addons/main/script_mod.hpp
  addons/medical/XEH_preInit.sqf
  addons/medical/functions/fnc_calcTreatmentTime.sqf
Labels: EricReview&Merge

#465 fix medical settings
  addons/medical/XEH_preInit.sqf
Labels: EricReview&Merge

#467 EdenModule bugfix
  addons/eden/functions/fnc_moduleLockDoors.sqf
  addons/stealthvehicle/configs/ExtendedEventHandlers.hpp
Labels: EricReview&Merge

#428 ExtensionCallback
  .gitignore
  TBModExtension_Logging.dll
  TBModExtension_Persistence.dll
  TBModExtension_x64.dll
  addons/eden/configs/CfgVehicles.hpp
  addons/eden/functions/fnc_moduleInjured.sqf
  addons/main/XEH_postInit.sqf
  addons/main/configs/ExtendedEventHandlers.hpp
  addons/main/functions/fnc_miscStuff.sqf
Labels: EricReview&Merge, kind/enhancement

#470 Flaggen CADPAT
  addons/skins/pictures/flags/Flagge_1.paa
  addons/skins/pictures/flags/Flagge_2.paa
  addons/skins/pictures/flags/Flagge_3.paa
  addons/skins/pictures/flags/Flagge_4.paa
  addons/skins/pictures/flags/Flagge_5.paa
  addons/skins/pictures/flags/Flagge_6.paa
  addons/skins/pictures/flags/Flagge_7.paa
  addons/skins/pictures/flags/Flagge_8.paa
  addons/skins/pictures/flags/Flagge_9.paa
Labels: WIP

#469 Heli-Pilotenhelme Panzerung
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
  addons/arsenal/functions/fnc_loadDefault.sqf
  addons/main/functions/fnc_miscStuff.sqf
  addons/rhs/CfgWeapons.hpp
Labels: WIP
