Repository TacticalBaconDevs/TBMod, pull requests merged in 2020-10, with the labels that each got.

#532 Debugbuild.txt Anpassung
  Debugbuild.txt
Labels: need review

#530 Safestart aktivieren wenn Mission beendet wird
  addons/zeus/config.cpp
  addons/zeus/configs/CfgFunctions.hpp
  addons/zeus/replacement/fnc_moduleEndMission.sqf
Labels: kind/enhancement, need review

#534 Setting fürEndMission Safestart
  addons/zeus/XEH_preInit.sqf
  addons/zeus/replacement/fnc_moduleEndMission.sqf
Labels: kind/enhancement, need review

#531 Poppy Einheiten zu Gruppen hinzufügen
  addons/poppy/config.cpp
  addons/poppy/configs/CfgGroups.hpp
Labels: kind/enhancement, need review

#538 Poppy Macro fix; isTBMission removed
  addons/advSlingload/XEH_postClientInit.sqf
  addons/advSlingload/XEH_postInit.sqf
  addons/advSlingload/XEH_preInit.sqf
  addons/arsenal/XEH_postClientInit.sqf
  addons/arsenal/XEH_preInit.sqf
  addons/building/XEH_preInit.sqf
  addons/eden/XEH_postClientInit.sqf
  addons/eden/XEH_preInit.sqf
  addons/eden/XEH_preServerInit.sqf
  addons/eos/XEH_postInit.sqf
  addons/eos/XEH_preInit.sqf
  addons/main/XEH_postClientInit.sqf
  addons/main/XEH_postInit.sqf
  addons/main/XEH_postServerInit.sqf
  addons/main/XEH_preInit.sqf
  addons/main/XEH_preServerInit.sqf
  addons/medical/XEH_preInit.sqf
  addons/nachschub/XEH_preInit.sqf
  addons/persistence/XEH_preInit.sqf
  addons/poppy/XEH_preInit.sqf
  addons/poppy/configs/CfgGroups.hpp
  addons/spectrum/XEH_postClientInit.sqf
  addons/spectrum/XEH_postServerInit.sqf
  addons/spectrum/XEH_preInit.sqf
  addons/stealthvehicle/XEH_preInit.sqf
  addons/taser/XEH_postInit.sqf
  addons/tasks/XEH_postServerInit.sqf
  addons/tasks/XEH_preInit.sqf
  addons/vz99/XEH_postInit.sqf
  addons/vz99/XEH_preInit.sqf
  addons/warlords/XEH_preInit.sqf
  addons/zeus/XEH_preInit.sqf
Labels: EricReview&Merge, need review

#535 TB Countermeasures
  addons/config/config.cpp
  addons/config/configs/CfgAmmo.hpp
  addons/config/configs/CfgMagazines.hpp
  addons/config/configs/CfgVehicles.hpp
  addons/config/configs/CfgWeapons.hpp
  addons/rhs/CfgAmmo.hpp
  addons/rhs/CfgMagazines.hpp
  addons/skins/pictures/pylons/TB_Pylons_UH_80.paa
Labels: WIP, needs testing

#536 [Snippets] Eron DefuseDrohne entschärfen
  infos/debugCode.sqf
Labels: EricReview&Merge, need review

#540 Texturen freigeschaltet und in Garage eingebaut
  addons/config/configs/CfgVehicles.hpp
  addons/config/configs/CfgWeapons.hpp
Labels: EricReview&Merge

#537 Recoilsystem überarbeiten
  addons/arsenal/arsenale/fnc_arsenalUK.sqf
  addons/main/XEH_PREP.hpp
  addons/main/XEH_postServerInit.sqf
  addons/main/functions/fnc_recoilCalc.sqf
  addons/main/functions/fnc_recoilSystem.sqf
  addons/main/functions/fnc_shortcuts.sqf
Labels: EricReview&Merge, need review

#539 Anpassungen des Blutabnehmens und der Näh/Heilzeit bei sich selbst
  addons/medical/XEH_PREP.hpp
  addons/medical/configs/ACE_Medical_Treatment_Actions.hpp
  addons/medical/functions/fnc_calcTreatmentTime.sqf
  addons/medical/functions/fnc_getBlood.sqf
Labels: EricReview&Merge, need review

#541 Wiesel2 AT from Beginning with HOT 3
  addons/config/configs/CfgVehicles.hpp
Labels: need review

#543 Mk45 Kadenz hoch, CamShake Effekte revidiert
  addons/config/configs/CfgAmmo.hpp
  addons/config/configs/CfgWeapons.hpp
Labels: EricReview&Merge, need review

#542 US an BW angeglichen: beides nun aktuell
  addons/arsenal/arsenale/fnc_arsenalBW.sqf
  addons/arsenal/functions/fnc_loadDefault.sqf
Labels: EricReview&Merge, need review

#545 Mk16/17 reformiert
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
  addons/nachschub/configs/CfgVehicles_USA.hpp
  addons/rhs/CfgAmmo.hpp
  addons/rhs/CfgMagazines.hpp
  addons/rhs/CfgWeapons.hpp
Labels: EricReview&Merge

#547 Scharfschützenüberarbeitung
  addons/arsenal/arsenale/fnc_arsenalUK.sqf
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
  addons/bw/configs/CfgAmmo.hpp
  addons/config/configs/CfgAmmo.hpp
  addons/config/configs/CfgMagazines.hpp
  addons/nachschub/configs/CfgVehicles_USA.hpp
  addons/rhs/CfgAmmo.hpp
  addons/rhs/CfgWeapons.hpp
  addons/rhs/config.cpp
Labels: EricReview&Merge

#548 Addon zum .338 Scharfschützengewehr
  addons/config/configs/CfgMagazineWells.hpp
  addons/rhs/CfgWeapons.hpp
Labels: kind/enhancement, need review
