Repository TacticalBaconDevs/TBMod, pull requests merged in 2020-01, with the labels that each got.

#398 Stealth Heli
  addons/stealthvehicle/ReadMe.md
  addons/stealthvehicle/XEH_PREP.hpp
  addons/stealthvehicle/XEH_preInit.sqf
  addons/stealthvehicle/config.cpp
  addons/stealthvehicle/configs/Cfg3DEN.hpp
  addons/stealthvehicle/configs/ExtendedEventHandlers.hpp
  addons/stealthvehicle/functions/fnc_handleFired.sqf
  addons/stealthvehicle/functions/fnc_handleGetIn.sqf
  addons/stealthvehicle/functions/fnc_handleGetOut.sqf
  addons/stealthvehicle/functions/fnc_handleHit.sqf
  addons/stealthvehicle/script_component.hpp
Labels: need review

#400 Persistence
  addons/persistence/XEH_PREP.hpp
  addons/persistence/functions/fnc_persistence.sqf
  addons/persistence/functions/fnc_persistenceBuilding.sqf
  addons/persistence/functions/fnc_persistenceObjects.sqf
  addons/persistence/functions/fnc_transferManager.sqf
Labels: need review, needs testing

#404 Wunsch von Culli
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
Labels: need review, question

#405 Panzerung+Beschleunigung
  addons/rhs/CfgVehicles.hpp
Labels: need review

#403 Neue Plates für neue Looks
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
Labels: need review

#378 Test Skins
  addons/rhs/CfgWeapons.hpp
  addons/rhs/config.cpp
  addons/skins/config.cpp
  addons/skins/configs/CfgEditorSubcategories.hpp
  addons/skins/configs/CfgVehicles.hpp
  addons/skins/configs/CfgWeapons.hpp
  addons/skins/pictures/uniforms/TB_Uniform_IS_1_black.paa
  addons/skins/pictures/vehicles/TB_Vehicles_RU_T-100_0.paa
  addons/skins/pictures/vehicles/TB_Vehicles_RU_T-100_1.paa
  addons/skins/pictures/vehicles/TB_Vehicles_RU_T-100_2.paa
  addons/skins/pictures/vehicles/TB_Vehicles_RU_T100_0.paa
  addons/skins/pictures/vehicles/TB_Vehicles_RU_T100_1.paa
  addons/skins/pictures/vehicles/TB_Vehicles_RU_T100_2.paa
  addons/skins/pictures/vests/TB_vest_IS_01A.paa
  addons/skins/pictures/vests/TB_vest_IS_01B.paa
Labels: need changes, needs testing

#401 Tasks
  addons/persistence/XEH_PREP.hpp
  addons/persistence/config.cpp
  addons/persistence/functions/fnc_persistence.sqf
  addons/persistence/functions/fnc_persistenceTasks.sqf
  addons/tasks/ReadMe.md
  addons/tasks/XEH_PREP.hpp
  addons/tasks/XEH_postServerInit.sqf
  addons/tasks/XEH_preInit.sqf
  addons/tasks/config.cpp
  addons/tasks/configs/ExtendedEventHandlers.hpp
  addons/tasks/functions/fnc_loadTask.sqf
  addons/tasks/functions/fnc_loop.sqf
  addons/tasks/script_component.hpp
Labels: need review, needs testing

#406 Archilles/Ares entfernt und ZEN eingefügt
  Debugbuild.txt
  TBMod_Builder.jar
  addons/building/functions/fnc_modifierShowVehicleType.sqf
  addons/building/functions/fnc_moduleKranFahrzeug.sqf
  addons/building/functions/fnc_moduleRessourcenFahrzeug.sqf
  addons/eden/functions/fnc_moduleInjured.sqf
  addons/main/config.cpp
  addons/main/configs/CfgMisc.hpp
  addons/main/functions/fnc_crashHelferClient.sqf
  addons/main/functions/fnc_miscStuff.sqf
  addons/main/functions/fnc_shortcuts.sqf
  addons/main/replacement/init.sqf
  addons/persistence/functions/fnc_modulepersistenceEDEN.sqf
  addons/persistence/functions/fnc_modulepersistencezeus.sqf
  addons/persistence/functions/fnc_persistence.sqf
  addons/persistence/functions/fnc_persistenceMarkers.sqf
  addons/persistence/functions/fnc_ping.sqf
  addons/persistence/functions/fnc_transferManager.sqf
  addons/zeus/functions/fnc_moduleAdjustCargoSpace.sqf
  addons/zeus/functions/fnc_moduleDefineAmmo.sqf
  addons/zeus/functions/fnc_moduleNachschubAbwurf.sqf
  addons/zeus/functions/fnc_moduleapplyLoadout.sqf
Labels: need review

#411 CarAlarm Module
  addons/eden/XEH_PREP.hpp
  addons/eden/config.cpp
  addons/eden/configs/CfgVehicles.hpp
  addons/eden/functions/fnc_moduleAtmoCarAlarm.sqf
Labels: need review

#409 Edenpreviews
  addons/skins/configs/CfgVehicles.hpp
  addons/skins/pictures/editorPreview/TB_Soldier_IS_1_black.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_BW_Hellcat.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_BW_Hellcat_2.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_BW_Merlin.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_BW_Pandur.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_BW_hunter.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_BW_hunter_smg.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_L159_Albatros.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_Leopard.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_Leopard_2.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_Merkava.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_PMC_Jeep.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_PMC_Jeep_2.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_PMC_Jeep_3.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_PMC_Pickup.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_PMC_SUV.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_Pandur.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_Strider.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_Strider_smg.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_T100.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_Wald_Patria_AMW.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_Wueste_Patria_AMW.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_hunter.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_hunter_smg.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_polizei_hellcat.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_polizei_hunter.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_sek_hellcat.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_sek_light.jpg
Labels: need review

#395 Indikatoren für Sanitäter an Ausrüstung (Helm/Rucksack)
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
  addons/arsenal/functions/fnc_loadDefault.sqf
  addons/main/configs/CfgVehicles.hpp
  addons/rhs/CfgMagazines.hpp
  addons/rhs/CfgVehicles.hpp
  addons/rhs/CfgWeapons.hpp
  addons/skins/configs/CfgVehicles.hpp
  addons/skins/pictures/backpacks/TB_backpacks_bergen_m81.paa
  addons/skins/pictures/backpacks/TB_backpacks_bergen_marpad_d.paa
  addons/skins/pictures/backpacks/TB_backpacks_bergen_marpad_wd.paa
  addons/skins/pictures/backpacks/TB_backpacks_bergen_urban.paa
  addons/skins/pictures/backpacks/TB_backpacks_kitbag_black.paa
  addons/skins/pictures/headgear/TB_headgear_SaniA01.paa
  addons/skins/pictures/headgear/TB_headgear_SaniA02.paa
  addons/skins/pictures/headgear/TB_headgear_SaniB01.paa
  addons/skins/pictures/headgear/TB_headgear_SaniB02.paa
  addons/skins/pictures/headgear/TB_headgear_SaniB03.paa
  addons/skins/pictures/headgear/TB_headgear_SaniC01.paa
  addons/skins/pictures/headgear/TB_headgear_SaniC02.paa
  addons/skins/pictures/headgear/TB_headgear_SaniC03.paa
Labels: need review

#415 Panzerung gegen UGL zu schwach
  addons/rhs/CfgVehicles.hpp
Labels: need review

#407 Poppy
  addons/poppy/ReadMe.md
  addons/poppy/XEH_PREP.hpp
  addons/poppy/XEH_preInit.sqf
  addons/poppy/config.cpp
  addons/poppy/configs/CfgEditorSubcategories.hpp
  addons/poppy/configs/CfgLoadouts.hpp
  addons/poppy/configs/CfgVehicles.hpp
  addons/poppy/configs/ExtendedEventHandlers.hpp
  addons/poppy/functions/fnc_addItems.sqf
  addons/poppy/functions/fnc_addMagazines.sqf
  addons/poppy/functions/fnc_applyLoadout.sqf
  addons/poppy/functions/fnc_findLoadableWeapon.sqf
  addons/poppy/functions/fnc_setEquipment.sqf
  addons/poppy/script_component.hpp
Labels: need review, needs testing

#410 ModuleLockDoors für Eden
  addons/eden/XEH_PREP.hpp
  addons/eden/config.cpp
  addons/eden/configs/CfgVehicles.hpp
  addons/eden/functions/fnc_moduleLockDoors.sqf
  addons/main/script_mod.hpp
Labels: need review

#416 Poppy Fix Vest
  addons/poppy/functions/fnc_setEquipment.sqf
Labels: need review

#420 Javelin Zoomspeed macht Visieren kaputt
  addons/rhs/CfgWeapons.hpp
Labels: kind/bug

#421 Fallschirme für alle Rollen
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
Labels: kind/bug

#419 Wiesel Skins/minor Tweaks
  addons/rhs/CfgVehicles.hpp
  addons/skins/configs/CfgVehicles.hpp
  addons/skins/pictures/editorPreview/TB_Vehicles_Wald_Wiesel_2_AT.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_Wald_Wiesel_2_MG.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_Wueste_Wiesel_2_AT.jpg
  addons/skins/pictures/editorPreview/TB_Vehicles_Wueste_Wiesel_2_MG.jpg
  addons/skins/pictures/vehicles/TB_Vehicles_Wiesel2_0.paa
  addons/skins/pictures/vehicles/TB_Vehicles_Wiesel2_1.paa
  addons/skins/pictures/vehicles/TB_Vehicles_Wiesel2_2.paa
  addons/skins/pictures/vehicles/TB_Vehicles_Wiesel2_3.paa
  addons/skins/pictures/vehicles/TB_Vehicles_Wiesel2_4.paa
  addons/skins/pictures/vehicles/TB_Vehicles_Wiesel2_5.paa
Labels: kind/enhancement

#422 MAAWS Magazine: InitSpeed angeglichen
  addons/rhs/CfgMagazines.hpp
Labels: kind/enhancement

#423 UAV Umbenennung: aus VAE wird USA
  addons/nachschub/configs/CfgVehicles_USA.hpp
  addons/rhs/CfgVehicles.hpp
Labels: kind/enhancement
