Repository TacticalBaconDevs/TBMod, pull requests merged in 2020-02, with the labels that each got.

#417 Automatisches FastRoping
  addons/eden/configs/Cfg3DEN.hpp
  addons/main/XEH_PREP.hpp
  addons/main/functions/fnc_fastRope.sqf
  addons/poppy/XEH_preInit.sqf
  addons/poppy/functions/fnc_applyLoadout.sqf
  addons/poppy/functions/fnc_findLoadableWeapon.sqf
  addons/poppy/functions/fnc_setEquipment.sqf
Labels: kind/enhancement, need review

#427 #settings ChatCommand
  addons/eos/XEH_PREP.hpp
  addons/eos/XEH_postInit.sqf
  addons/main/XEH_PREP.hpp
  addons/main/functions/fnc_chatCommands.sqf
  addons/main/functions/fnc_fileExists.sqf
  addons/main/functions/fnc_transfer.sqf
  addons/main/functions/fnc_transferVar.sqf
Labels: kind/enhancement, need review, needs testing

#430 Multitarn, Desert, Woodland Bergen Rucksäcke
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
  addons/skins/configs/CfgVehicles.hpp
  addons/skins/pictures/backpacks/TB_backpacks_bergen_multitarn.paa
Labels: kind/enhancement

#431 FastRope bugfix
  addons/building/functions/fnc_clearPlaceables.sqf
  addons/eden/configs/Cfg3DEN.hpp
  addons/main/functions/fnc_fastRope.sqf
Labels: kind/bug

#375 Anpassungen Russ Arsenal
  addons/arsenal/arsenale/fnc_arsenalRUSS.sqf
  addons/arsenal/functions/fnc_loadDefault.sqf
  addons/arsenal/functions/fnc_modifierMainAction.sqf
Labels: need review

#435 Nachschubsanpassungen/Gruppierungen/UK-Kisten
  addons/nachschub/XEH_preInit.sqf
  addons/nachschub/configs/CfgVehicles.hpp
  addons/nachschub/configs/CfgVehicles_UK.hpp
Labels: kind/enhancement, need review

#436 Cameraview extended for various Bombs/Rockets
  addons/rhs/CfgAmmo.hpp
  addons/rhs/CfgMagazines.hpp
Labels: kind/enhancement

#437 Wechsel zu RHS DAGR von Vanilla Hydra
  addons/rhs/CfgAmmo.hpp
  addons/rhs/CfgMagazines.hpp
Labels: EricReview&Merge, kind/enhancement, need review

#438 UGV Rauch
  addons/main/XEH_preInit.sqf
  addons/main/configs/CfgAmmo.hpp
  addons/main/configs/CfgMagazines.hpp
  addons/main/configs/CfgVehicles.hpp
  infos/debugCode.sqf
Labels: EricReview&Merge, need review

#441 Fix Cfg3DEN.hpp Marko
  addons/eden/configs/Cfg3DEN.hpp
Labels: kind/bug, need review

#445 Module Injured Damage
  addons/eden/configs/CfgVehicles.hpp
  addons/eden/functions/fnc_moduleInjured.sqf
Labels: kind/enhancement
