Repository TacticalBaconDevs/TBMod, pull requests merged in 2020-11, with the labels that each got.

#551 neues Mittleres MG, Kisten umorganisiert
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
  addons/arsenal/arsenale/fnc_arsenalVANILLA.sqf
  addons/config/configs/CfgAmmo.hpp
  addons/config/configs/CfgMagazineWells.hpp
  addons/config/configs/CfgMagazines.hpp
  addons/config/configs/CfgWeapons.hpp
  addons/nachschub/configs/CfgVehicles.hpp
  addons/nachschub/configs/CfgVehicles_USA.hpp
  addons/rhs/CfgWeapons.hpp
Labels: EricReview&Merge, kind/enhancement, need review

#552 M27 iar
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
  addons/nachschub/configs/CfgVehicles.hpp
  addons/nachschub/configs/CfgVehicles_BW.hpp
  addons/nachschub/configs/CfgVehicles_RUSS.hpp
  addons/nachschub/configs/CfgVehicles_UK.hpp
  addons/nachschub/configs/CfgVehicles_USA.hpp
  addons/rhs/CfgAmmo.hpp
  addons/rhs/CfgMagazineWells.hpp
  addons/rhs/CfgMagazines.hpp
  addons/rhs/CfgWeapons.hpp
Labels: EricReview&Merge, kind/enhancement

#553 VTOL Gunship
  addons/config/configs/CfgMagazines.hpp
  addons/config/configs/CfgVehicles.hpp
  addons/config/configs/CfgWeapons.hpp
Labels: EricReview&Merge, kind/enhancement

#556 Flaggen und Tafeln überarbeitet
  addons/main/pics/Alpha.paa
  addons/main/pics/Bravo.paa
  addons/main/pics/Charlie.paa
  addons/main/pics/Comcenter.paa
  addons/main/pics/Delta.paa
  addons/main/pics/Echo.paa
  addons/main/pics/Foxtrott.paa
  addons/main/pics/Gamma.paa
  addons/main/pics/Logistik.paa
  addons/main/pics/Logistiksp.paa
  addons/main/pics/OneTeam.paa
  addons/main/pics/briefing.paa
  addons/main/pics/logo.paa
  addons/main/pics/sammelplatz.paa
  addons/main/pics/trupp.paa
  addons/main/pics/waffenausgabe.paa
  addons/skins/pictures/flags/Flagge_1.paa
  addons/skins/pictures/flags/Flagge_2.paa
  addons/skins/pictures/flags/Flagge_3.paa
  addons/skins/pictures/flags/Flagge_4.paa
  addons/skins/pictures/flags/Flagge_5.paa
  addons/skins/pictures/flags/Flagge_6.paa
  addons/skins/pictures/flags/Flagge_7.paa
  addons/skins/pictures/flags/Flagge_8.paa
  addons/skins/pictures/flags/Flagge_9.paa
Labels: need review

#559 SPS Helm in Multi/OCP und weitere Tweaks
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
  addons/config/configs/CfgMagazines.hpp
  addons/config/configs/CfgWeapons.hpp
  addons/skins/configs/CfgWeapons.hpp
  addons/skins/pictures/headgear/TB_headgear_sps_ocp.paa
Labels: kind/enhancement

#558 Fix Bastionzone
  addons/eos/core/fnc_bastionCore.sqf
Labels: kind/bug, need review

#562 Callsign Lynx
  addons/main/configs/CfgVehicles.hpp
Labels: help wanted, kind/enhancement, need review, needs testing

#549 LDF Anpassungen für Coop Event
  addons/arsenal/arsenale/themen/fnc_arsenalLDF.sqf
  addons/arsenal/functions/fnc_loadDefault.sqf
  addons/arsenal/functions/fnc_modifierMainAction.sqf
  addons/main/functions/fnc_doorBreach.sqf
  addons/nachschub/configs/CfgVehicles.hpp
  addons/nachschub/configs/CfgVehicles_LDF.hpp
Labels: need review, needs testing

#564 Mine detector
  addons/arsenal/arsenale/fnc_arsenalBW.sqf
  addons/arsenal/arsenale/fnc_arsenalRUSS.sqf
  addons/arsenal/arsenale/fnc_arsenalUK.sqf
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
  addons/arsenal/arsenale/fnc_arsenalVANILLA.sqf
  addons/config/configs/CfgWeapons.hpp
Labels: EricReview&Merge, kind/enhancement, need review

#563 vz99 & microDAGR fuer vers. Arsenale
  addons/arsenal/arsenale/fnc_arsenalRUSS.sqf
  addons/arsenal/arsenale/fnc_arsenalUK.sqf
  addons/arsenal/arsenale/fnc_arsenalVANILLA.sqf
  addons/arsenal/arsenale/themen/fnc_arsenalLDF.sqf
Labels: EricReview&Merge

#572 M200 Tracer Munition für LDF Mission
  addons/arsenal/arsenale/themen/fnc_arsenalLDF.sqf
  addons/arsenal/functions/fnc_loadDefault.sqf
  addons/config/configs/CfgAmmo.hpp
  addons/config/configs/CfgMagazineWells.hpp
  addons/config/configs/CfgMagazines.hpp
  addons/nachschub/configs/CfgVehicles_LDF.hpp
Labels: kind/enhancement, need review
