Repository TacticalBaconDevs/TBMod, pull requests merged in 2021-04, with the labels that each got.

#624 Leuchtspurpatronen in Magazinen
  addons/rhs/CfgMagazines.hpp
Labels: kind/enhancement, need review

#625 Scar Leuchtspur als letzte Patronen, überflüssiges Magazin raus
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
  addons/rhs/CfgMagazines.hpp
Labels: kind/enhancement, need review

#622 Fixed Poppy Spawn
  addons/poppy/configs/CfgGroups.hpp
Labels: need review

#626 IOTV OCP Westen eingefügt
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
  addons/rhs/CfgWeapons.hpp
Labels: kind/enhancement, need review

#628 Westenupdate vervollständigt
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
  addons/config/configs/CfgVehicles.hpp
  addons/config/configs/CfgWeapons.hpp
  addons/rhs/CfgWeapons.hpp
  addons/skins/configs/CfgVehicles.hpp
  addons/skins/configs/CfgWeapons.hpp
  addons/skins/pictures/backpacks/TB_backpacks_kitbag_black.paa
  addons/skins/pictures/vests/TB_black_vest_mbav_01.paa
  addons/skins/pictures/vests/TB_black_vest_spc_01.paa
  addons/skins/pictures/vests/TB_black_vest_ucp_01.paa
Labels: kind/enhancement, need review

#629 Little Bird und Cobra Update
  addons/rhs/CfgMagazines.hpp
  addons/rhs/CfgVehicles.hpp
Labels: kind/enhancement, need review

#630 Fehlerbehebung bei AH-1Z
  addons/rhs/CfgVehicles.hpp
Labels: kind/enhancement, need review

#627 GM Arsenal auf 90er Updaten
  addons/arsenal/arsenale/themen/fnc_arsenalBRD.sqf
  addons/arsenal/functions/fnc_loadDefault.sqf
  addons/arsenal/functions/fnc_modifierMainAction.sqf
  addons/nachschub/configs/CfgVehicles.hpp
  addons/nachschub/configs/CfgVehicles_BRD.hpp
Labels: WIP
