Repository TacticalBaconDevs/TBMod, pull requests merged in 2021-03, with the labels that each got.

#609 Panzerung erhöht, sichtbarer Hülsenauswurf für 40mm, zusätzliche APFS…
  addons/config/config.cpp
  addons/config/configs/CfgCloudlets.hpp
  addons/config/configs/CfgMagazines.hpp
  addons/config/configs/CfgWeapons.hpp
  addons/skins/configs/CfgVehicles_FV510Warrior.hpp
Labels: kind/enhancement, need review

#611 Fixed: Vanilla Cargo Inventare werden nicht mehr richtig gelöscht
  addons/eden/configs/Cfg3DEN.hpp
  addons/main/functions/fnc_clearArmaInv.sqf
Labels: EricReview&Merge, kind/bug

#612 new fileExists cmd
  addons/main/functions/fnc_fileExists.sqf
Labels: EricReview&Merge

#615 MK_17 Recoilfix; Ersatztank
  addons/main/functions/fnc_recoilCalc.sqf
  addons/nachschub/configs/CfgVehicles.hpp
Labels: EricReview&Merge

#618 Rückstoß, Westen, NVG Wide, Warrior, Magazine, Default Layouts
  addons/arsenal/arsenale/fnc_arsenalBW.sqf
  addons/arsenal/arsenale/fnc_arsenalUK.sqf
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
  addons/arsenal/functions/fnc_loadDefault.sqf
  addons/config/configs/CfgRecoils.hpp
  addons/config/configs/CfgWeapons.hpp
  addons/main/functions/fnc_miscStuff.sqf
  addons/main/functions/fnc_recoilCalc.sqf
  addons/nachschub/configs/CfgVehicles_USA.hpp
  addons/rhs/CfgWeapons.hpp
  addons/skins/configs/CfgVehicles_FV510Warrior.hpp
Labels: kind/enhancement, need review
