Repository TacticalBaconDevs/TBMod, pull requests merged in 2021-11, with the labels that each got.

#661 Thermal Monogoggle
  addons/rhs/CfgWeapons.hpp
Labels: kind/enhancement, need review

#660 MRCO hinzugefügt
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
Labels: kind/enhancement, need review

#662 Vector für Arzt und Pilot
  addons/arsenal/arsenale/fnc_arsenalUSA.sqf
Labels: EronReview&Merge, need review

#666 #664 Blacklist und CustomNames; fpsMonitor ausmachbar
  addons/arsenal/XEH_postClientInit.sqf
  addons/arsenal/configs/CfgVehicles.hpp
  addons/arsenal/functions/fnc_getRollenName.sqf
  addons/arsenal/functions/fnc_modifierMainAction.sqf
  addons/config/configs/CfgWeaponHandling.hpp
  addons/main/XEH_preInit.sqf
  addons/main/functions/fnc_miscStuff.sqf
  addons/stealthvehicle/ReadMe.md
Labels: EronReview&Merge, need review

#659 MPR nach RHS verschoben
  addons/config/configs/CfgMagazineWells.hpp
  addons/config/configs/CfgMagazines.hpp
  addons/config/configs/CfgWeapons.hpp
  addons/rhs/CfgMagazineWells.hpp
  addons/rhs/CfgMagazines.hpp
  addons/rhs/CfgWeapons.hpp
Labels: kind/enhancement, need review, needs testing

#670 Feuermodus angepasst
  addons/config/configs/CfgWeapons.hpp
Labels: WIP

#669 AW159 Wildcat
  addons/config/configs/CfgMagazines.hpp
  addons/config/configs/CfgVehicles.hpp
  addons/config/configs/CfgWeapons.hpp
  addons/skins/configs/CfgVehicles.hpp
  addons/skins/configs/CfgVehicles_AW159Wildcat.hpp
  addons/skins/pictures/vehicles/TB_Vehicles_AW159_Wildcat.paa
Labels: kind/enhancement, need review
